#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

require __DIR__ . '/autoload.php';

defined('YII_DEBUG') or define('YII_DEBUG', $_ENV['YII_DEBUG']);
defined('YII_ENV') or define('YII_ENV', $_ENV['YII_ENV']);

require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
  require __DIR__ . '/common/config/main.php',
  require __DIR__ . '/common/config/main-local.php',
  require __DIR__ . '/console/config/main.php',
  require __DIR__ . '/console/config/main-local.php'
);

$config = YII_ENV_TEST ? yii\helpers\ArrayHelper::merge(
  $config,
  require __DIR__ . '/common/config/test.php',
  require __DIR__ . '/common/config/test-local.php',
  require __DIR__ . '/console/config/test.php',
  require __DIR__ . '/console/config/test-local.php'
) : $config;

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
